import type { AppItemType } from '../.vitepress/types'
import env from '../.vitepress/config/env'

export default <AppItemType[]>[
  {
    name: 'SensibleSideButtons',
    intro: '修复 macOS 中残废的鼠标侧键，恢复在 Windows 中顺畅的前进/后退',
    link: 'https://sensible-side-buttons.archagon.net/',
    icon: 'sensible-side-buttons.webp',
    category: '系统增强',
    updated: '2023-03-01',
    charge: '免费开源',
    size: '1.7 MB',
    chip: ['AppleChip'],
    tags: ['增强鼠标侧键'],
  },
  {
    name: 'Scroll Reverser',
    intro: '反转滚动方向，对触控板和鼠标进行独立设置',
    link: 'https://pilotmoon.com/scrollreverser/',
    icon: 'scroll-reverser.webp',
    category: '系统增强',
    updated: '2023-02-25',
    charge: '免费开源',
    size: '2.6 MB',
    chip: ['AppleChip'],
    tags: ['滚动翻转'],
  },
  {
    name: 'ClashX Pro',
    intro: '简单轻量化的代理客户端',
    link: 'https://install.appcenter.ms/users/clashx/apps/clashx-pro/distribution_groups/public',
    icon: 'clashx.webp',
    category: '网络代理',
    updated: '2023-02-25',
    charge: '免费',
    size: '23.63MB',
    chip: ['AppleChip'],
    tags: ['科学上网'],
  },
  {
    name: 'SwitchHosts',
    intro: '方便快捷的管理/切换 Host 文件',
    link: 'https://swh.app/',
    icon: 'switchhosts.webp',
    category: '系统增强',
    updated: '2022-12-12',
    charge: '免费开源',
    size: '81.8MB',
    chip: ['AppleChip', 'Windows', 'Linux'],
    tags: ['科学上网'],
  },
  {
    name: 'Pixelmator Pro',
    intro: '简单易用的专业图像编辑工具',
    link: 'https://www.pixelmator.com/pro/',
    icon: 'pixelmator-pro.webp',
    category: '图像编辑',
    updated: '2022-12-12',
    charge: '免费7天+买断',
    size: '81.8MB',
    chip: ['AppleChip'],
    tags: [],
  },
  {
    name: 'Keka',
    intro: '小巧轻便的文件压缩工具',
    link: 'http://www.keka.io/zh-cn/',
    icon: 'keka.webp',
    category: '系统增强',
    updated: '2022-12-12',
    charge: '自愿付费',
    size: '36.4MB',
    chip: ['AppleChip'],
    tags: ['文件压缩'],
  },
  {
    name: 'SnippetsLab',
    intro: '代码片段 + Markdown 管理工具',
    link: 'https://www.renfei.org/snippets-lab/',
    icon: 'snippets-lab.webp',
    category: '效率工具',
    updated: '2022-12-12',
    charge: '买断',
    size: '50.5MB',
    chip: ['AppleChip'],
    tags: ['代码片段', 'Markdown'],
  },
  {
    name: 'Rectangle Pro',
    intro: '使用键盘快捷键来移动/调整窗口大小',
    link: 'https://rectangleapp.com/pro',
    icon: 'rectangle-pro.webp',
    category: '系统增强',
    updated: '2022-12-11',
    charge: '免费10天+买断',
    chip: ['AppleChip'],
    size: '14.7MB',
    tags: ['窗口调整'],
  },
  {
    name: 'HapiGo',
    intro: '多合一启动器，即时搜索、快速预览及直接启动',
    link: 'https://hapigo.com/',
    icon: 'hapigo.webp',
    category: '效率工具',
    updated: '2022-12-11',
    charge: '免费+订阅',
    size: '31.8MB',
    chip: ['AppleChip'],
    tags: ['启动器', '剪贴板', '翻译'],
  },
  {
    name: 'HyperSwitch',
    intro: '还原 Windows 窗口切换',
    link: 'https://bahoom.com/hyperswitch',
    icon: 'hyperswitch.webp',
    category: '系统增强',
    updated: '2022-12-11',
    charge: '免费',
    size: '2.2 MB',
    chip: ['AppleChip'],
    tags: ['窗口切换'],
  },
  {
    name: 'Karabiner Elements',
    intro: '键盘/鼠标改键工具',
    link: 'https://karabiner-elements.pqrs.org/',
    icon: 'karabiner-elements.webp',
    category: '系统增强',
    updated: '2022-12-11',
    charge: '免费',
    size: '20.7 MB',
    chip: ['AppleChip'],
    tags: ['改键'],
  },
  {
    name: 'MacCopier',
    intro: '自动复制短信验证码到剪贴板',
    link: 'https://github.com/DreamSaddle/MacCopier',
    icon: 'maccopier.webp',
    category: '系统增强',
    updated: '2022-12-11',
    charge: '免费开源',
    size: '20.7 MB',
    chip: ['AppleChip'],
    tags: [],
  },
  {
    name: '图压',
    intro: '简单易用的图片压缩软件',
    link: 'https://tuya.xinxiao.tech/',
    icon: 'tuya.webp',
    category: '效率工具',
    updated: '2022-12-11',
    charge: '免费开源',
    size: '75.1MB',
    chip: ['AppleChip', 'Windows'],
    tags: ['图片压缩'],
  },
  {
    name: 'Android 文件传输',
    intro: '在 Mac 电脑和 Android 设备之间浏览和传输文件',
    link: 'https://tuya.xinxiao.tech/',
    icon: 'usbfistman.webp',
    category: '系统增强',
    updated: '2022-12-11',
    charge: '免费',
    size: '3.7 MB',
    chip: ['AppleChip'],
    tags: ['文件传输'],
  },
  {
    name: 'MenubarX',
    intro: 'Mac 菜单栏浏览器，可以在菜单栏固定任何网页',
    link: 'https://menubarx.app/',
    icon: 'menubarx.webp',
    category: '效率工具',
    updated: '2022-12-11',
    charge: '免费+买断',
    size: '8 MB',
    chip: ['AppleChip'],
    tags: ['浏览器', '菜单栏增强'],
  },
  {
    name: 'OpenEmu',
    intro: '多合一掌机/街机模拟器，包括但不限于 GBA/NDS/FC/PSP/……',
    link: 'https://openemu.org/',
    icon: 'openemu.webp',
    category: '游戏工具',
    updated: '2022-12-11',
    charge: '免费开源',
    size: '32MB',
    chip: ['AppleChip'],
    tags: ['游戏机模拟器'],
  },
  {
    name: 'Shottr',
    intro: '屏幕截图工具，支持取色/贴图/标注/测量/OCR/无痕打码/滚动截图……',
    link: 'https://shottr.cc/',
    icon: 'shottr.webp',
    category: '系统增强',
    updated: '2022-12-11',
    charge: '免费',
    size: '1.3MB',
    chip: ['AppleChip'],
    tags: ['屏幕截图', '图片打码', 'OCR'],
  },
].map(v => ({
  ...v,
  icon: `${env.IMG_BASE_URL}app-icon/${v.icon}`,
}))
